"""Added flight table

Revision ID: a9b7b37c28ff
Revises: 17e0098c0ae9
Create Date: 2022-10-24 08:53:38.898042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b7b37c28ff'
down_revision = '17e0098c0ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dep_time', sa.DateTime(), nullable=True),
    sa.Column('flight_code', sa.String(length=64), nullable=True),
    sa.Column('dest', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
